;; css-mode
(setq css-indent-offset 2)

;; yasnippet
(setq css-default-values
      '(("background-attachment" . "fixed")
        ("background-color" . "transparent")
        ("background-repeat" . "no-repeat")
        ("border" . "none")
        ("border-top" . "none")
        ("border-radius" . "100%")
        ("border-right" . "none")
        ("border-bottom" . "none")
        ("border-left" . "none")
        ("bottom" . "0")
        ("box-sizing" . "border-box")
        ("clear" . "both")
        ("content" . "\"\"")
        ("cursor" . "pointer")
        ("display" . "none")
        ("float" . "left")
        ("font-style" . "normal")
        ("font-weight" . "normal")
        ("height" . "100%")
        ("left" . "0")
        ("list-style-type" . "none")
        ("margin" . "0")
        ("margin-top" . "0")
        ("margin-right" . "0")
        ("margin-bottom" . "0")
        ("margin-left" . "0")
        ("opacity" . "0")
        ("overflow" . "hidden")
        ("padding" . "0")
        ("padding-top" . "0")
        ("padding-right" . "0")
        ("padding-bottom" . "0")
        ("padding-left" . "0")
        ("right" . "0")
        ("text-decoration" . "none")
        ("position" . "relative")
        ("text-align" . "right")
        ("text-decoration" . "none")
        ("text-transform" . "uppercase")
        ("top" . "0")
        ("visibility" . "hidden")
        ("width" . "100%")
        ))
(defun get-css-default-value-c (prop pairs)
  (cond
   ((null pairs) "value")
   ((string-equal prop (car (car pairs))) (cdr (car pairs)))
   (t (get-css-default-value-c prop (cdr pairs)))))
(defun get-css-default-value (prop)
  (get-css-default-value-c (replace-regexp-in-string "^-[a-zA-Z]+-" "" prop) css-default-values))
